"toggle_console" "`"
"Mouse Left" "-move_y w"
"weapon_previous" "Mouse Wheel Down"
"-move_x" "a"
"weapon_fire" "Mouse Left"
"move_z" "space"
"toggle_menu" "escape"
"toggle_editor" "c"
"move_x" "d"
"look_x" "Mouse X"
"-look_y" "Mouse Y"
"-move_z" "shift"
"open_console" "224"
"weapon_next" "Mouse Wheel Up"
"weapon_fire_alt" "Mouse Right"
"-move_y" "s"
"move_y" "w"
"editor_mode_add" "x"
"editor_mode_remove" "z"