"d" "move_x"
"224" "toggle_console"
"`" "toggle_console"
"a" "-move_x"
"Mouse X" "-weapon_next"
"Mouse X" "look_x"
"Mouse Right" "weapon_fire_alt"
"escape" "toggle_menu"
"space" "move_z"
"shift" "-move_z"
"Mouse Y" "look_y"
"Mouse Left" "weapon_fire"
"Mouse Wheel Down" "weapon_previous"
"w" "move_y"
"s" "-move_y"
"Mouse Wheel Up" "weapon_next"
"c" "toggle_editor"
